from app.api.v1 import auth
from app.api.v1 import user
from app.api.v1 import products
from app.api.v1 import category
from app.api.v1 import publisher
from app.api.v1 import author
from app.api.v1 import address
from app.api.v1 import upload
from app.api.v1 import checkout
from app.api.v1 import orders
from app.api.v1 import coupon
from app.api.v1 import cart
from app.api.v1 import review
from app.api.v1 import dashboard
