# coding=utf-8
UPLOAD_EXTENSIONS = ['.jpg', '.png', '.jpeg']
PATH_IMAGE = 'app/static/images/'
SUPER_ADMIN_ID = '5fc5f970100333097e15017b'
URL_SERVER = "http://localhost:5000"
PATH_IMAGE_SERVER = URL_SERVER + '/images/'
DEFAULT_BOOK_COVER = PATH_IMAGE_SERVER + 'default_book_cover.jpg'
PRODUCT_NOT_FOUND_MSG = 'Không tìm thấy sản phẩm!'
PRODUCT_NOT_ENOUGH_MSG = 'Sản phẩm {} chỉ còn {} sản phẩm!'
ADD_TO_CART_SUCCESSFULLY_MSG = 'Thêm sản phẩm vào giỏ thành công!'
EMTPY_CART_MSG = 'Không có sản phẩm nào trong giỏ hàng của bạn.'
ADDRESS_NOT_FOUND_MSG = 'Địa chỉ không đúng. Vui lòng kiểm tra lại!'
CURD_ERR_MSG = 'Đã có lỗi xảy ra khi {} {}!'
CURD_SUCCESS_MSG = '{} {} thành công!'
NOT_FOUND_MSG = 'Không tìm thấy {}'
